// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu6LgPe5lZwNsnJXNvmW5ARqvUpwKSNok',
    appId: '1:253583446682:web:1092f3e4259abbe9a68523',
    messagingSenderId: '253583446682',
    projectId: 'ssms-revamp-final',
    authDomain: 'ssms-revamp-final.firebaseapp.com',
    storageBucket: 'ssms-revamp-final.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0qYHgReGd5-m3MkKGZdLZxEaFkSTonxU',
    appId: '1:253583446682:android:7f78f12940911d8aa68523',
    messagingSenderId: '253583446682',
    projectId: 'ssms-revamp-final',
    storageBucket: 'ssms-revamp-final.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOFcywdMXLPoIqnp2hyAK8_WuYcfly-cs',
    appId: '1:253583446682:ios:faefe29ac6ace410a68523',
    messagingSenderId: '253583446682',
    projectId: 'ssms-revamp-final',
    storageBucket: 'ssms-revamp-final.appspot.com',
    iosClientId: '253583446682-oplmcosf2rlob55mfg9qsokaj0g9tv97.apps.googleusercontent.com',
    iosBundleId: 'gupta.aryan.com.ssmsRevamp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOFcywdMXLPoIqnp2hyAK8_WuYcfly-cs',
    appId: '1:253583446682:ios:faefe29ac6ace410a68523',
    messagingSenderId: '253583446682',
    projectId: 'ssms-revamp-final',
    storageBucket: 'ssms-revamp-final.appspot.com',
    iosClientId: '253583446682-oplmcosf2rlob55mfg9qsokaj0g9tv97.apps.googleusercontent.com',
    iosBundleId: 'gupta.aryan.com.ssmsRevamp',
  );
}
